version: "3.1"
services:
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data 777
    environment:
      - "POSTGRES_DB=SplitterDb"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
    networks:
      - "splitter"
  splitter:
    image: splitter
    ports:
      - "9000:9000"
    environment:
      - "POSTGRES_DB=SplitterDb"
      - "DB_USER=user"
      - "DB_PASSWORD=password"
      - "CLIENT_ID="
      - "CLIENT_SECRET="
    networks:
      - "splitter"
    depends_on:
      - "database"
networks:
  splitter:
    external: true