version: "3.1"
services:
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data 777
    environment:
      - "POSTGRES_DB=SplitterDb"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"