= Praktikum
:icons: font
:icon-set: fa
:source-highlighter: rouge
:experimental:

== Organisatorisches

Die finden die URL für das Webex System auf http://propra.de/ws2223/ab899545cb7e0df[dieser Seite]. Wir hoffen, dass die Webex-URL über das ganze Praktikum über gleich bleibt, können aber nicht ausschließen, dass es Änderungen geben muss.

Wenn es wichtige Ankündigungen zum Praktikum gibt, werden wir diese sowohl im Diskussionsforum als auch auf der URL Seite online stellen.

IMPORTANT: Verwenden Sie in Webex als Display-Name Ihren Namen und in Klammern dahinter das GitHub-Login. Beispiel: `William Bruce Rose (axl62)`.

Sie können Ihren Namen in der Teilnehmerliste über den „Edit Display Name”-Menüpunkt ändern. In der App finden Sie den Menüpunkt durch Rechtsklick auf Ihren Namen, im Browser über die drei Punkte neben dem Namen.

=== Aufgabenstellung

Die Beschreibung der Aufgabe finden Sie in link:aufgabe.adoc[diesem Dokument].

=== Ergänzungen zur Aufgabenstellung

Es gibt zwei geplante Ergänzungen zur Aufgabenstellung. Sie erhalten die erste Ergänzung (Beschreibung von Testszenarien) am 02.03.2023 vor Beginn der Praktikumszeit. Die zweite Ergänzung (Einbau einer neuen Funktionalität) erhalten Sie am 08.03.2023 vor Beginn der Praktikumszeit.

Die Ergänzungsaufgaben werden wir auf der http://propra.de/ws2223/ab899545cb7e0df[URL Seite] verlinken.

=== Deadlines

Wir beginnen mit einer Teilbegutachtung der Anwendung am 14.03.2023 ab 13:00 Uhr. Zu diesem Zeitpunkt muss die Anwendung bis auf die Persistenz fertig sein. Die komplette Anwendung muss am 17.03.2023 um 13:00 Uhr fertiggestellt sein.

== Fragen und Hilfestellungen

Für Fragen gibt es zum einen die Diskussionsforen, die Sie unbedingt bei Fragen verwenden müssen, die auch für andere Teilnehmer:innen interessant seien könnten.

* Fragen zu organisatoischen Themen stellen Sie bitte im Forum https://github.com/hhu-propra2-ws22/Organisation/discussions/categories/fragen-zur-organisation[Fragen zur Organisation].
* Für Fragen zur Aufgabenstellung haben wir ein neues Forum https://github.com/hhu-propra2-ws22/Organisation/discussions/categories/fragen-zur-aufgabestellung[Fragen zur Aufgabenstellung] erstellt.
* Wenn Sie Fragen zum Stoff der Vorlesung haben, stellen Sie diese bitte weiterhin im Forum https://github.com/hhu-propra2-ws22/Organisation/discussions/categories/fachliche-fragen[Fachliche Fragen]

Außerdem werden Sie von unseren Tutor:innen regelmäßig besucht und haben dort ebenfalls die Gelegenheit, Fragen zu stellen. Kristin, Leonie und Jens kommen Sie auch gelegentlich besuchen oder helfen aus, wenn besonders schwierige Fragen auftreten sollten.

Bei Fragen, die Sie selber persönlich betreffen (zum Beispiel bei Krankmeldungen), wenden Sie sich bitte per Mail an mailto:propra@cs.hhu.de[propra@cs.hhu.de]. Stellen Sie dort bitte keine Fragen, die auch in den Foren geklärt werden könnten.

== Verhaltensregeln

Wir erwarten von Ihnen einen respektvollen Umgang miteinander. Es gilt grundsätzlich bei uns der https://berlincodeofconduct.org/de/[Berlin Code of Conduct]. Die Tutor:innen haben die Aufgabe, die Einhaltung der Regeln zu überwachen und können bei Verstößen gegen den Verhaltenskodex Personen aus dem Praktikum ausschließen. Ein Praktikumsausschluss hat zur Folge, dass Sie das Modul in diesem Semester nicht mehr abschließen können.

= Dokumentation
:icons: font
:icon-set: fa
:source-highlighter: rouge
:experimental:

== A.Nutzungsanweisung

Zuerst klonen Sie sich das Repository von GitHub. Dann erstellen Sie eine neue OAuth-App über GitHub. Dazu folgen Sie folgenden Schritten:
Profil -> Settings -> Developer Settings -> OAuth Apps -> New Oauth App

Als Application Name verwenden Sie "Splitter". Die Url, sowie Callback URL lauten "http://localhost:9000/"
Dann können Sie die Application registrieren. Nun müssen Sie die Client-ID kopieren, sowie ein Client-Secret generieren als auch speichern.

Navigieren Sie in den Ordner "projekt_gruppe39/Splitter" und öffnen sie die Datei "docker-compose.yaml" mit einem Editor Ihrer Wahl. 
Tragen Sie Ihre vorher generierten Client-ID und Client-Secret in die Umgebungsvariablen "CLIENT_ID", sowie "CLIENT SECRET" ein und speichern Sie die Datei.
Öffnen Sie ein Terminal im gleichen Ordner und führen Sie folgende Befehle in gleicher Reihenfolge aus (Docker sollte bereits gestartet sein):

* "docker network create splitter"
* "docker build -t splitter ."
* "docker-compose up"

Wenn Sie alles richtig gemacht haben, sollten sowohl Anwendung, als auch Datenbank in einem virtuellen Netzwerk gestartet worden sein.
Die Anwendung ist im Browser unter der URL "http://localhost:9000/" erreichbar.

== B:Arch42

Die vollständige Dokumentation finden Sie in link:documentation.adoc[diesem Dokument].
