logging:
  level:
    org:
      springframework:
        security: info

spring:
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:postgresql://database:5432/SplitterDb

  security:
      oauth2:
        client:
          registration:
            github:
              client-id: ${CLIENT_ID}
              client-secret: ${CLIENT_SECRET}
              scope: read:public_repo
server:
  port: 9000